# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest


steps:

- task: SSH@0
  inputs:
    sshEndpoint: 'lakshmivm'
    runOptions: 'inline'
    inline: 'mkdir  /home/lakshmi/krishna'

    readyTimeout: '20000'

- task: SSH@0
  inputs:
    sshEndpoint: 'lakshmivm'
    runOptions: 'inline'
    inline: 'touch  /home/lakshmi/krishna/lalitha'

    readyTimeout: '20000'

- task: SSH@0
  inputs:
    sshEndpoint: 'lakshmivm'
    runOptions: 'inline'
    inline: 'git add /home/lakshmi/krishna'

    readyTimeout: '20000'

- task: SSH@0
  inputs:
    sshEndpoint: 'lakshmivm'
    runOptions: 'inline'
    inline: 'git commit -m  /home/lakshmi/krishna'

    readyTimeout: '20000'

