# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

 
- task: SSH@0
  inputs:
    sshEndpoint: 'vkdvm'
    runOptions: 'inline'
    inline: |
        sudo systemctl restart apache2 -y'
        sed s/\/.*$//'sudo apt-get install curl'curl http://icanhazip.com
        sudo apt-get install mysql-server'mysql_secre_installation
        sudo apt-get install php libapache2-mod-php php-mcrypt php-mysql
        sudo systemctl restart apache2
        sudo systemctl status apache2
        apt-cache search php- | less'apt-cache show package_name
        apt-cache show php-cli
        sudo apt-get install php-cli
      