# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

 
- task: SSH@0
  inputs:
    sshEndpoint: 'vkdvm'
    runOptions: 'inline'
    inline: |
        sudo systemctl restart apache2 -y
        curl http://icanhazip.com
        sudo apt-get install mysql-server -y
        sudo apt-get install php libapache2-mod-php php-mcrypt php-mysql -y
        sudo systemctl restart apache2
        sudo systemctl status apache2
        sudo apt-get install php-cli -y
      